<?php
// File: exams.php
/**
 * Exams management: schedule, seat/room assignment, question headers and printing.
 */
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/academic_year_helpers.php';
require_once __DIR__ . '/includes/exams_helper.php';
require_once __DIR__ . '/includes/school_roles.php';
ensure_school_roles_schema();
if (!current_teacher_is_executive()) require_permission('manage_reports');
ensure_exams_schema();
$tab=$_GET['tab']??'schedule'; $year=resolve_academic_year_request($_GET['year']??get_current_academic_year()); // v4.38.0 unified
if ($_SERVER['REQUEST_METHOD']==='POST') {
 if(!verify_csrf($_POST['csrf_token']??'')){set_flash_message('error','خطای CSRF');redirect('exams.php');}
 if(isset($_POST['mark_printed'])){ DB::execute('UPDATE exam_schedules SET is_printed=? WHERE id=?', [isset($_POST['is_printed'])?1:0, (int)$_POST['exam_id']]); set_flash_message('success','وضعیت چاپ آزمون ذخیره شد.'); redirect('exams.php?tab=print&year='.urlencode($year)); }
 if(isset($_POST['copy_class_design'])){
  $src=(int)($_POST['source_exam_id']??0); $target=explode('|', $_POST['target_assignment']??'');
  if(count($target)>=3){
    [$tyear,$tclass,$tsubject]=$target; $srcExam=DB::fetch('SELECT * FROM exam_schedules WHERE id=?',[$src]); $design=DB::fetch('SELECT * FROM exam_designs WHERE exam_id=?',[$src]);
    if($srcExam && $design){
      $teacherId=(int)$srcExam['teacher_id']; $teacherName=$srcExam['teacher_name']; $grade=infer_grade_from_class_name($tclass);
      $dst=DB::fetch("SELECT id FROM exam_schedules WHERE exam_kind='class' AND academic_year=? AND class_name=? AND subject_name=? AND teacher_id=? LIMIT 1",[$tyear,$tclass,$tsubject,$teacherId]);
      if(!$dst){ DB::execute("INSERT INTO exam_schedules (academic_year,exam_month,grade_level,class_name,subject_name,teacher_id,teacher_name,exam_date_jalali,exam_day_name,start_time,duration_minutes,exam_room_default,question_file,header_config,is_active,exam_kind,created_at_jalali) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[$tyear,'آزمون کلاسی',$grade,$tclass,$tsubject,$teacherId,$teacherName,'','','',45,'',$srcExam['question_file'],$srcExam['header_config'] ?: '{}',1,'class',jdate('Y/m/d H:i')]); $dstId=DB::lastInsertId(); }
      else { $dstId=(int)$dst['id']; DB::execute('UPDATE exam_schedules SET question_file=?, header_config=? WHERE id=?',[$srcExam['question_file'],$srcExam['header_config'],$dstId]); }
      $cacheDir=__DIR__.'/uploads/exams/pdf-pages/exam_'.$dstId; foreach(glob($cacheDir.'/*')?:[] as $cf) if(is_file($cf)) @unlink($cf);
      $ex=DB::fetch('SELECT id FROM exam_designs WHERE exam_id=?',[$dstId]);
      if($ex) DB::execute('UPDATE exam_designs SET design_json=?,designer_teacher_id=?,designer_name=?,saved_by_admin_id=?,updated_at_jalali=? WHERE exam_id=?',[$design['design_json'],$design['designer_teacher_id'],$design['designer_name'],$_SESSION['admin_id']??null,jalali_now(),$dstId]);
      else DB::execute('INSERT INTO exam_designs (exam_id,design_json,designer_teacher_id,designer_name,saved_by_admin_id,updated_at_jalali) VALUES (?,?,?,?,?,?)',[$dstId,$design['design_json'],$design['designer_teacher_id'],$design['designer_name'],$_SESSION['admin_id']??null,jalali_now()]);
      set_flash_message('success','طراحی آزمون کلاسی برای کلاس/درس مقصد اعمال شد.');
    }
  }
  redirect('exams.php?tab=print&year='.urlencode($year));
 }
 if(isset($_POST['save_exam'])){
  $id=(int)($_POST['exam_id']??0); $tid=(int)($_POST['teacher_id']??0); $tname=''; if($tid){$t=DB::fetch('SELECT full_name FROM teachers WHERE id=?',[$tid]);$tname=$t['full_name']??'';}
  $file=$_POST['existing_question_file']??'';
  if(isset($_FILES['question_file']) && $_FILES['question_file']['error']===UPLOAD_ERR_OK){$ext=strtolower(pathinfo($_FILES['question_file']['name'],PATHINFO_EXTENSION)); if(in_array($ext,['pdf','png','jpg','jpeg','webp'])){$dir=__DIR__.'/uploads/exams'; if(!is_dir($dir))mkdir($dir,0755,true); $fn='question_'.time().'_'.bin2hex(random_bytes(3)).'.'.$ext; move_uploaded_file($_FILES['question_file']['tmp_name'],$dir.'/'.$fn); $file='uploads/exams/'.$fn;}}
  $p=[unify_academic_year(trim($_POST['academic_year']??$year)),trim($_POST['grade_level']??''),trim($_POST['class_name']??''),trim($_POST['subject_name']??''),$tid?:null,$tname,trim($_POST['exam_date_jalali']??''),trim($_POST['start_time']??''),(int)($_POST['duration_minutes']??90),trim($_POST['exam_room_default']??''),$file,json_encode($_POST['header']??[],JSON_UNESCAPED_UNICODE)];
  if($id) DB::execute('UPDATE exam_schedules SET academic_year=?,grade_level=?,class_name=?,subject_name=?,teacher_id=?,teacher_name=?,exam_date_jalali=?,start_time=?,duration_minutes=?,exam_room_default=?,question_file=?,header_config=? WHERE id=?',array_merge($p,[$id]));
  else DB::execute('INSERT INTO exam_schedules (academic_year,grade_level,class_name,subject_name,teacher_id,teacher_name,exam_date_jalali,start_time,duration_minutes,exam_room_default,question_file,header_config,created_at_jalali) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',array_merge($p,[jdate('Y/m/d H:i')]));
  set_flash_message('success','برنامه امتحانی ذخیره شد.'); redirect('exams.php?tab=schedule&year='.urlencode($p[0]));
 }
 if(isset($_POST['create_grade_exams'])){
  $y=unify_academic_year(trim($_POST['academic_year']??$year)); $month=trim($_POST['exam_month']??'خرداد'); $grade=trim($_POST['grade_level']??'');
  $enabled=$_POST['enabled_subjects']??[]; $globalClasses=$_POST['enabled_classes']??[]; $created=0;
  foreach($enabled as $key){
    [$subject,$teacherId]=array_pad(explode('|',$key,2),2,'0');
    $date=trim($_POST['date'][$key]??''); $day=trim($_POST['day'][$key]??''); $time=trim($_POST['time'][$key]??''); $duration=(int)($_POST['duration'][$key]??90);
    if($subject===''||$date===''||$time==='') continue;
    $enabledClasses = $_POST['classes'][$key] ?? $globalClasses;
    foreach($enabledClasses as $className){
      $className=norm_class_str($className); if($className==='') continue;
      $teacherName=''; $tid=(int)$teacherId;
      if($tid){$t=DB::fetch('SELECT full_name FROM teachers WHERE id=?',[$tid]);$teacherName=$t['full_name']??'';}
      if(!$tid){$row=DB::fetch('SELECT teacher_id, teacher_name FROM class_schedules WHERE academic_year=? AND class_name=? AND subject_name=? AND teacher_id IS NOT NULL LIMIT 1',[$y,$className,$subject]); $tid=(int)($row['teacher_id']??0); $teacherName=$row['teacher_name']??'';}
      DB::execute('INSERT INTO exam_schedules (academic_year,exam_month,grade_level,class_name,subject_name,teacher_id,teacher_name,exam_date_jalali,exam_day_name,start_time,duration_minutes,is_active,created_at_jalali) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',[$y,$month,$grade,$className,$subject,$tid?:null,$teacherName,$date,$day,$time,$duration,1,jdate('Y/m/d H:i')]);
      $created++;
    }
  }
  set_flash_message('success',tr_num($created,'fa').' آزمون برای پایه/کلاس‌های انتخابی فعال شد.'); redirect('exams.php?tab=schedule&year='.urlencode($y));
 }
 if(isset($_POST['assign_bulk'])){
  $y=unify_academic_year(trim($_POST['academic_year']??$year)); $month=trim($_POST['exam_month']??'خرداد'); $room=trim($_POST['exam_room']??''); $start=(int)($_POST['seat_start']??1); $ids=array_map('intval',$_POST['student_ids']??[]); $i=0;
  foreach($ids as $sid){$seat=tr_num((string)($start+$i),'en'); DB::execute('INSERT INTO exam_student_seating (academic_year,exam_month,student_id,seat_number,exam_room,created_at_jalali) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE seat_number=VALUES(seat_number), exam_room=VALUES(exam_room)',[$y,$month,$sid,$seat,$room,jdate('Y/m/d H:i')]); $i++;}
  set_flash_message('success',tr_num($i,'fa').' شماره صندلی/کلاس امتحانی مستقل از آزمون اختصاص یافت.'); redirect('exams.php?tab=assign&year='.urlencode($y).'&exam_month='.urlencode($month));
 }
}
if(isset($_GET['delete'])){DB::execute('DELETE FROM exam_schedules WHERE id=?',[(int)$_GET['delete']]);DB::execute('DELETE FROM exam_assignments WHERE exam_id=?',[(int)$_GET['delete']]);set_flash_message('success','امتحان حذف شد.');redirect('exams.php');}
require_once __DIR__ . '/includes/header.php';
$exams=DB::fetchAll('SELECT es.*, COALESCE(t.full_name, es.teacher_name) t_name FROM exam_schedules es LEFT JOIN teachers t ON t.id=es.teacher_id WHERE es.academic_year=? ORDER BY es.exam_date_jalali, es.start_time',[$year]);
$classes=get_unified_class_options($year); $grades=get_unified_grade_options($year); $teachers=DB::fetchAll('SELECT id,full_name FROM teachers WHERE status=1 ORDER BY full_name');
$edit=isset($_GET['edit'])?DB::fetch('SELECT * FROM exam_schedules WHERE id=?',[(int)$_GET['edit']]):null; $selectedExam=(int)($_GET['exam_id']??($exams[0]['id']??0));
$examMonth = trim($_GET['exam_month'] ?? 'خرداد');
$selectedGrade = trim($_GET['grade_level'] ?? ($grades[0]['grade_level'] ?? ''));
$selectedClassFilter = trim($_GET['class_name'] ?? '');
$sortMode = trim($_GET['sort'] ?? 'name');
$gradeSubjects = exam_subjects_for_grade($year, $selectedGrade);
$gradeClasses = array_values(array_filter($classes, fn($c)=>$selectedGrade==='' || infer_grade_from_class_name($c['class_name'])===$selectedGrade || ($c['grade_level']??'')===$selectedGrade));
?>
<div class="space-y-6"><?php /* v4.61.0: teacher hero + app-style grid on every teacher page */ require_once __DIR__ . '/includes/teacher_nav.php'; render_teacher_nav(); ?><div class="page-hero flex justify-between items-center"><div><h2 class="text-2xl font-bold">📝 امتحانات</h2><p class="text-sm text-muted">مدیریت برنامه امتحانی، صندلی، کلاس امتحان و چاپ سربرگ سوالات</p></div><div class="flex gap-2"><a class="btn <?php echo $tab==='schedule'?'btn-primary':'btn-outline'; ?>" href="exams.php?tab=schedule&year=<?php echo urlencode($year); ?>">برنامه امتحانی</a><a class="btn <?php echo $tab==='assign'?'btn-primary':'btn-outline'; ?>" href="exams.php?tab=assign&year=<?php echo urlencode($year); ?>">صندلی و کلاس</a><a class="btn <?php echo $tab==='print'?'btn-primary':'btn-outline'; ?>" href="exams.php?tab=print&year=<?php echo urlencode($year); ?>">چاپ</a><?php if(!(function_exists('current_teacher_is_executive') && current_teacher_is_executive() && !is_admin_logged_in())): ?><a class="btn btn-warning" href="exam-question-bank.php">بانک سوالات</a><?php endif; ?></div></div>
<?php if($tab==='schedule'): ?>
<div class="card compact-exam-builder">
  <form method="GET" class="grid grid-cols-4 gap-3 items-end mb-3"><input type="hidden" name="tab" value="schedule"><div><label class="text-xs">سال تحصیلی (انتخابی)</label><select name="year" class="form-select font-bold" onchange="this.form.submit()">
                        <?php foreach(get_academic_years_for_filter() as $yy): ?>
                            <option value="<?php echo clean($yy['academic_year']); ?>" <?php echo $year===$yy['academic_year']?'selected':''; ?>><?php echo clean($yy['academic_year']); ?><?php echo !empty($yy['is_default'])?' - پیش‌فرض':''; ?></option>
                        <?php endforeach; ?>
                    </select></div><div><label class="text-xs">ماه امتحانی</label><select name="exam_month" class="form-select"><?php foreach(['مهر','آبان','آذر','دی','بهمن','اسفند','فروردین','اردیبهشت','خرداد','شهریور'] as $m): ?><option value="<?php echo $m; ?>" <?php echo $examMonth===$m?'selected':''; ?>><?php echo $m; ?></option><?php endforeach; ?></select></div><div><label class="text-xs">پایه</label><select name="grade_level" class="form-select"><?php foreach($grades as $g): ?><option value="<?php echo clean($g['grade_level']); ?>" <?php echo $selectedGrade===$g['grade_level']?'selected':''; ?>><?php echo clean($g['grade_level']); ?></option><?php endforeach; ?></select></div><button class="btn btn-primary">نمایش دروس پایه</button></form>
  <form method="POST"><input type="hidden" name="csrf_token" value="<?php echo csrf_token(); ?>"><input type="hidden" name="create_grade_exams" value="1"><input type="hidden" name="academic_year" value="<?php echo clean($year); ?>"><input type="hidden" name="exam_month" value="خرداد"><input type="hidden" name="grade_level" value="<?php echo clean($selectedGrade); ?>">
    <div class="grid grid-cols-2 gap-3"><div><b>دروس برنامه هفتگی پایه <?php echo clean($selectedGrade); ?></b><div class="table-container max-h-[350px]"><table><thead><tr><th>فعال</th><th>درس</th><th>دبیر خودکار</th><th>تاریخ/روز/ساعت</th></tr></thead><tbody><?php foreach($gradeSubjects as $gs): $key=$gs['subject_name'].'|'.($gs['teacher_id']??0); ?><tr><td><input type="checkbox" name="enabled_subjects[]" value="<?php echo clean($key); ?>"></td><td class="font-bold"><?php echo clean($gs['subject_name']); ?><div class="text-xs text-muted">کلاس‌های این درس:</div><div class="flex flex-wrap gap-1"><?php foreach($gradeClasses as $gc): ?><label class="text-xs"><input type="checkbox" name="classes[<?php echo clean($key); ?>][]" value="<?php echo clean($gc['class_name']); ?>" checked> <?php echo clean($gc['class_name']); ?></label><?php endforeach; ?></div></td><td><?php echo clean($gs['teacher_name'] ?: 'از برنامه هفتگی'); ?></td><td><input class="form-input" name="date[<?php echo clean($key); ?>]" placeholder="1404/03/01"><input class="form-input" name="day[<?php echo clean($key); ?>]" placeholder="شنبه"><input class="form-input" name="time[<?php echo clean($key); ?>]" placeholder="08:00"><input class="form-input" name="duration[<?php echo clean($key); ?>]" value="90"><small class="text-xs">فایل سوالات پس از ایجاد آزمون از بخش ویرایش تکی بارگذاری می‌شود.</small></td></tr><?php endforeach; if(!$gradeSubjects): ?><tr><td colspan="4" class="text-center text-muted">برای این پایه در برنامه هفتگی درسی یافت نشد.</td></tr><?php endif; ?></tbody></table></div></div><div><b>کلاس‌های فعال آزمون در این پایه</b><div class="table-container max-h-[350px]"><table><thead><tr><th>فعال</th><th>کلاس</th></tr></thead><tbody><?php foreach($gradeClasses as $gc): ?><tr><td><input type="checkbox" name="enabled_classes[]" value="<?php echo clean($gc['class_name']); ?>" checked></td><td class="font-bold"><?php echo clean($gc['class_name']); ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
    <button class="btn btn-success mt-3">فعال‌سازی آزمون‌های انتخاب‌شده</button>
  </form>
</div>
<div class="grid grid-cols-3 gap-6"><div class="card"><h3 class="font-bold mb-3"><?php echo $edit?'ویرایش امتحان':'تعریف امتحان تکی/اصلاحی'; ?></h3><form method="POST" enctype="multipart/form-data" class="space-y-3"><input type="hidden" name="csrf_token" value="<?php echo csrf_token(); ?>"><input type="hidden" name="save_exam" value="1"><input type="hidden" name="exam_id" value="<?php echo (int)($edit['id']??0); ?>"><input type="hidden" name="existing_question_file" value="<?php echo clean($edit['question_file']??''); ?>"><select name="academic_year" class="form-select font-bold">
                        <option value="">انتخاب سال تحصیلی...</option>
                        <?php foreach(get_academic_years_for_filter() as $yy): ?>
                            <option value="<?php echo clean($yy['academic_year']); ?>" <?php echo ($edit['academic_year']??$year)===$yy['academic_year']?'selected':''; ?>><?php echo clean($yy['academic_year']); ?></option>
                        <?php endforeach; ?>
                    </select><select name="grade_level" class="form-select"><option value="">همه پایه/از کلاس</option><?php foreach($grades as $g): ?><option value="<?php echo clean($g['grade_level']); ?>" <?php echo ($edit['grade_level']??'')===$g['grade_level']?'selected':''; ?>><?php echo clean($g['grade_level']); ?></option><?php endforeach; ?></select><select name="class_name" class="form-select"><option value="">همه کلاس‌های پایه</option><?php foreach($classes as $c): ?><option value="<?php echo clean($c['class_name']); ?>" <?php echo ($edit['class_name']??'')===$c['class_name']?'selected':''; ?>><?php echo clean($c['class_name']); ?></option><?php endforeach; ?></select><select name="subject_name" class="form-select" required><option value="">انتخاب درس از برنامه هفتگی</option><?php foreach($gradeSubjects as $gs): ?><option value="<?php echo clean($gs['subject_name']); ?>" <?php echo ($edit['subject_name']??'')===$gs['subject_name']?'selected':''; ?>><?php echo clean($gs['subject_name'].' - '.($gs['teacher_name']?:'دبیر برنامه')); ?></option><?php endforeach; ?></select><select name="teacher_id" class="form-select"><option value="0">دبیر خودکار/انتخاب دستی</option><?php foreach($teachers as $t): ?><option value="<?php echo $t['id']; ?>" <?php echo ($edit['teacher_id']??0)==$t['id']?'selected':''; ?>><?php echo clean($t['full_name']); ?></option><?php endforeach; ?></select><input name="exam_date_jalali" class="form-input" required placeholder="1404/03/10" value="<?php echo clean($edit['exam_date_jalali']??''); ?>"><input name="start_time" class="form-input" required placeholder="08:00" value="<?php echo clean($edit['start_time']??''); ?>"><input name="duration_minutes" type="number" class="form-input" value="<?php echo clean($edit['duration_minutes']??90); ?>"><input name="exam_room_default" class="form-input" placeholder="کلاس/سالن پیش‌فرض" value="<?php echo clean($edit['exam_room_default']??''); ?>"><label class="text-xs">فایل سوالات بدون سربرگ PDF/تصویر</label><input type="file" name="question_file" class="form-input" accept=".pdf,.png,.jpg,.jpeg,.webp"><button class="btn btn-success w-full">ذخیره امتحان</button></form></div><div class="card col-span-2"><div class="table-container"><table><thead><tr><th>تاریخ</th><th>ساعت</th><th>پایه/کلاس</th><th>درس</th><th>دبیر</th><th>عملیات</th></tr></thead><tbody><?php foreach($exams as $e): ?><tr><td><?php echo tr_num($e['exam_date_jalali'],'fa'); ?></td><td><?php echo tr_num($e['start_time'],'fa'); ?></td><td><?php echo clean(($e['grade_level']?:'').' '.$e['class_name']); ?></td><td class="font-bold"><?php echo clean($e['subject_name']); ?></td><td><?php echo clean($e['t_name']); ?></td><td><a class="btn btn-secondary text-xs" href="exams.php?tab=schedule&edit=<?php echo $e['id']; ?>">ویرایش</a><a class="btn btn-danger text-xs" onclick="return confirm('حذف؟')" href="exams.php?delete=<?php echo $e['id']; ?>">حذف</a></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php elseif($tab==='assign'):
$students = DB::fetchAll("SELECT * FROM students WHERE status='active'");
if ($selectedGrade !== '') $students = array_values(array_filter($students, fn($s)=>($s['grade_level']===$selectedGrade || infer_grade_from_class_name($s['class_name'])===$selectedGrade)));
if ($selectedClassFilter !== '') $students = array_values(array_filter($students, fn($s)=>$s['class_name']===$selectedClassFilter));
if ($sortMode==='class') persian_usort_classes($students,'class_name','grade_level'); else persian_usort_students($students);
?>
<div class="card"><form method="GET" class="grid grid-cols-6 gap-3 items-end"><input type="hidden" name="tab" value="assign"><div><label class="text-xs">سال تحصیلی (انتخابی)</label><select name="year" class="form-select font-bold" onchange="this.form.submit()">
                        <?php foreach(get_academic_years_for_filter() as $yy): ?>
                            <option value="<?php echo clean($yy['academic_year']); ?>" <?php echo $year===$yy['academic_year']?'selected':''; ?>><?php echo clean($yy['academic_year']); ?></option>
                        <?php endforeach; ?>
                    </select></div><div><label class="text-xs">ماه امتحانی</label><select name="exam_month" class="form-select"><?php foreach(['مهر','آبان','آذر','دی','بهمن','اسفند','فروردین','اردیبهشت','خرداد','شهریور'] as $m): ?><option value="<?php echo $m; ?>" <?php echo $examMonth===$m?'selected':''; ?>><?php echo $m; ?></option><?php endforeach; ?></select></div><div><label class="text-xs">پایه</label><select name="grade_level" class="form-select"><option value="">همه</option><?php foreach($grades as $g): ?><option value="<?php echo clean($g['grade_level']); ?>" <?php echo $selectedGrade===$g['grade_level']?'selected':''; ?>><?php echo clean($g['grade_level']); ?></option><?php endforeach; ?></select></div><div><label class="text-xs">کلاس</label><select name="class_name" class="form-select"><option value="">همه</option><?php foreach($classes as $c): ?><option value="<?php echo clean($c['class_name']); ?>" <?php echo $selectedClassFilter===$c['class_name']?'selected':''; ?>><?php echo clean($c['class_name']); ?></option><?php endforeach; ?></select></div><div><label class="text-xs">مرتب‌سازی</label><select name="sort" class="form-select"><option value="name" <?php echo $sortMode==='name'?'selected':''; ?>>نام خانوادگی</option><option value="class" <?php echo $sortMode==='class'?'selected':''; ?>>پایه/کلاس</option></select></div><button class="btn btn-primary">نمایش</button></form></div>
<form method="POST" class="card"><input type="hidden" name="csrf_token" value="<?php echo csrf_token(); ?>"><input type="hidden" name="assign_bulk" value="1"><input type="hidden" name="academic_year" value="<?php echo clean($year); ?>"><input type="hidden" name="exam_month" value="<?php echo clean($examMonth); ?>"><div class="grid grid-cols-3 gap-3 mb-4"><input name="exam_room" class="form-input" placeholder="کلاس امتحانی مستقل"><input name="seat_start" class="form-input" value="1" placeholder="شروع شماره صندلی"><button class="btn btn-success">اختصاص به انتخاب‌شده‌ها</button></div><div class="table-container"><table><thead><tr><th><input type="checkbox" onclick="document.querySelectorAll('.ex-st').forEach(c=>c.checked=this.checked)"></th><th>نام</th><th>کلاس</th><th>صندلی/کلاس فعلی</th></tr></thead><tbody><?php foreach($students as $s): $as=DB::fetch('SELECT * FROM exam_student_seating WHERE academic_year=? AND exam_month=? AND student_id=?',[$year,$examMonth,$s['id']]); ?><tr><td><input class="ex-st" type="checkbox" name="student_ids[]" value="<?php echo $s['id']; ?>"></td><td class="font-bold"><?php echo clean($s['last_name'].'، '.$s['first_name']); ?></td><td><?php echo clean($s['class_name']); ?></td><td><?php echo clean(($as['exam_room']??'').' / '.($as['seat_number']??'')); ?></td></tr><?php endforeach; ?></tbody></table></div></form>
<?php else: ?><div class="card"><h3 class="font-bold mb-3">چاپ برنامه، سوالات و کارت صندلی</h3><div class="flex gap-2 mb-3"><a target="_blank" class="btn btn-success" href="exam-print.php?type=seatcards&year=<?php echo urlencode($year); ?>&exam_month=<?php echo urlencode($examMonth); ?>">چاپ کارت صندلی ماه <?php echo clean($examMonth); ?></a></div><div class="table-container"><table><thead><tr><th>امتحان</th><th>برنامه جدولی</th><th>طراحی سوال کلاس</th><th>سوالات با سربرگ</th><th>چاپ پایه‌ای (همه کلاس‌های پایه)</th><th>چاپ شده؟</th></tr></thead><tbody><?php foreach($exams as $e): $eGradeLevel = trim($e['grade_level'] ?? '') ?: infer_grade_from_class_name($e['class_name'] ?? ''); ?><tr><td><?php echo clean($e['subject_name'].' - '.$e['exam_date_jalali'].' - '.$e['class_name']); ?></td><td><a target="_blank" class="btn btn-primary text-xs" href="exam-print.php?type=schedule&exam_id=<?php echo $e['id']; ?>">چاپ برنامه</a></td><td><a target="_blank" class="btn btn-success text-xs" href="exam-print.php?type=questions&exam_id=<?php echo $e['id']; ?>&dt=<?php echo urlencode(make_exam_design_token($e['id'], is_admin_logged_in() ? 'admin' : 'exec', $_SESSION['admin_id'] ?? ($_SESSION['teacher_id'] ?? 0))); ?>">طراحی اختصاصی این کلاس</a></td><td><a target="_blank" class="btn btn-warning text-xs" href="exam-print.php?type=questions&exam_id=<?php echo $e['id']; ?>&dt=<?php echo urlencode(make_exam_design_token($e['id'], is_admin_logged_in() ? 'admin' : 'exec', $_SESSION['admin_id'] ?? ($_SESSION['teacher_id'] ?? 0))); ?>">چاپ سربرگ سوالات</a></td><td><?php /* v4.69.0: چاپ پایه‌ای — همان طراحی برای همه دانش‌آموزان همه کلاس‌های پایه */ if ($eGradeLevel !== ''): ?><a target="_blank" class="btn btn-primary text-xs" title="طراحی این آزمون برای تمام دانش‌آموزان همه کلاس‌های پایه <?php echo clean($eGradeLevel); ?> تکثیر و چاپ می‌شود" href="exam-print.php?type=questions&exam_id=<?php echo $e['id']; ?>&grade_all=1&dt=<?php echo urlencode(make_exam_design_token($e['id'], is_admin_logged_in() ? 'admin' : 'exec', $_SESSION['admin_id'] ?? ($_SESSION['teacher_id'] ?? 0))); ?>">چاپ برای کل پایه <?php echo clean($eGradeLevel); ?></a><?php else: ?><span class="text-xs text-muted">پایه نامشخص</span><?php endif; ?></td><td><form method="POST"><input type="hidden" name="csrf_token" value="<?php echo csrf_token(); ?>"><input type="hidden" name="mark_printed" value="1"><input type="hidden" name="exam_id" value="<?php echo $e['id']; ?>"><label class="text-xs"><input type="checkbox" name="is_printed" onchange="this.form.submit()" <?php echo !empty($e['is_printed'])?'checked':''; ?>> بله</label></form></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php $classExams=DB::fetchAll("SELECT es.*, d.updated_at_jalali, d.designer_name FROM exam_schedules es JOIN exam_designs d ON d.exam_id=es.id WHERE es.exam_kind='class' ORDER BY es.id DESC LIMIT 200"); ?>
<div class="card mt-4"><h3 class="font-bold mb-3">آزمون‌های کلاسی طراحی‌شده</h3><div class="table-container"><table><thead><tr><th>دبیر/درس/کلاس</th><th>آخرین طراحی</th><th>چاپ/ویرایش</th><th>استفاده برای کلاس دیگر همان دبیر</th><th>چاپ شده؟</th></tr></thead><tbody><?php foreach($classExams as $ce): $teacherAssignments=DB::fetchAll("SELECT DISTINCT academic_year,class_name,subject_name FROM class_schedules WHERE teacher_id=? ORDER BY academic_year DESC,class_name,subject_name",[(int)$ce['teacher_id']]); ?><tr><td><?php echo clean($ce['designer_name'].' - '.$ce['subject_name'].' - '.$ce['class_name']); ?></td><td><?php echo tr_num($ce['updated_at_jalali'],'fa'); ?></td><td><a target="_blank" class="btn btn-primary text-xs" href="exam-print.php?type=questions&exam_id=<?php echo $ce['id']; ?>&dt=<?php echo urlencode(make_exam_design_token($ce['id'], is_admin_logged_in()?'admin':'exec', $_SESSION['admin_id'] ?? ($_SESSION['teacher_id'] ?? 0))); ?>">مشاهده/چاپ</a></td><td><form method="POST" class="flex gap-1"><input type="hidden" name="csrf_token" value="<?php echo csrf_token(); ?>"><input type="hidden" name="copy_class_design" value="1"><input type="hidden" name="source_exam_id" value="<?php echo $ce['id']; ?>"><select name="target_assignment" class="form-select text-xs"><?php foreach($teacherAssignments as $ta): ?><option value="<?php echo clean($ta['academic_year'].'|'.$ta['class_name'].'|'.$ta['subject_name']); ?>"><?php echo clean($ta['academic_year'].' - '.$ta['class_name'].' - '.$ta['subject_name']); ?></option><?php endforeach; ?></select><button class="btn btn-success text-xs">اعمال</button></form></td><td><form method="POST"><input type="hidden" name="csrf_token" value="<?php echo csrf_token(); ?>"><input type="hidden" name="mark_printed" value="1"><input type="hidden" name="exam_id" value="<?php echo $ce['id']; ?>"><label class="text-xs"><input type="checkbox" name="is_printed" onchange="this.form.submit()" <?php echo !empty($ce['is_printed'])?'checked':''; ?>> بله</label></form></td></tr><?php endforeach; if(!$classExams): ?><tr><td colspan="5" class="text-center text-muted">آزمون کلاسی طراحی‌شده‌ای وجود ندارد.</td></tr><?php endif; ?></tbody></table></div></div><?php endif; ?></div>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
